version: "3"
services:
    fc-db:
        image: mysql:8
        container_name: fc-db
        restart: always
        env_file:
            - ".env"
        ports:
          - '3306:3306'
        expose:
            - 3306
